# Generated by Django 6.0.4 on 2026-04-21 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=20, unique=True)),
                ('room_name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('meeting', 'ห้องประชุม'), ('classroom', 'ห้องเรียน')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ห้อง',
                'verbose_name_plural': 'ห้อง',
                'ordering': ['room_code'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu_username', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('lecturer', 'อาจารย์'), ('admin', 'เจ้าหน้าที่')], default='lecturer', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ผู้ใช้งาน',
                'verbose_name_plural': 'ผู้ใช้งาน',
            },
        ),
    ]
