# Generated by Django 6.0.4 on 2026-04-28 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='curriculum',
            field=models.CharField(blank=True, choices=[('regular', 'ปริญญาตรีภาคปกติ'), ('master', 'ปริญญาโท'), ('tep_tepe', 'TEP-TEPE'), ('tu_pine', 'TU-PINE')], max_length=20, null=True, verbose_name='หลักสูตร'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='days_of_week',
            field=models.CharField(max_length=50, verbose_name='วันในสัปดาห์'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(verbose_name='ถึงวันที่'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(verbose_name='ถึงเวลา'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='purpose_type',
            field=models.CharField(choices=[('class', 'สอนปกติ/ชดเชย/เสริม'), ('training', 'จัดอบรม/จัดติว')], max_length=20, verbose_name='วัตถุประสงค์'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Users.room', verbose_name='ห้อง'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(verbose_name='ตั้งแต่วันที่'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(verbose_name='ตั้งแต่เวลา'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสวิชา'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อวิชา'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อเรื่อง'),
        ),
        migrations.CreateModel(
            name='BlackoutPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อช่วงปิด')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blackout_periods', to=settings.AUTH_USER_MODEL)),
                ('rooms', models.ManyToManyField(blank=True, related_name='blackout_periods', to='Users.room', verbose_name='ห้องที่ปิด (ว่าง = ทุกห้อง)')),
            ],
            options={
                'verbose_name': 'ช่วงเวลาปิดใช้งาน',
                'verbose_name_plural': 'ช่วงเวลาปิดใช้งาน',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_booking', 'มีการจองใหม่ (แจ้ง Admin)'), ('status_change', 'สถานะการจองเปลี่ยน (แจ้งผู้จอง)'), ('reminder', 'แจ้งเตือนล่วงหน้า 1 วัน')], max_length=30)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Users.booking')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือน',
                'ordering': ['-created_at'],
            },
        ),
    ]
